services:
  api:
    build:
      context: .
      dockerfile: src/RealEstate.API/Dockerfile.prod
    container_name: realestate-api
    ports:
      - "7269:5268"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=realestate;Username=realestateuser;Password=123
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5268
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - realestate-network
    volumes:
      - realestate-images:/app/wwwroot/images
      - realestate-dataprotection:/root/.aspnet/DataProtection-Keys # Added for data protection keys
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5268/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5 # Increased for robustness
      start_period: 60s # Increased to allow more startup time

volumes:
  postgres-data:
    name: realestate-postgres-data
  realestate-images:
    name: realestate-images
  realestate-dataprotection: # Added volume
    name: realestate-dataprotection

networks:
  realestate-network:
    name: realestate-network