version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: realestate-postgres
    environment:
      POSTGRES_DB: realestate
      POSTGRES_USER: realestateuser
      POSTGRES_PASSWORD: 123
    ports:
      - "7432:5432"  # Using uncommon external port
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - realestate-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U realestateuser -d realestate"]
      interval: 10s
      timeout: 5s
      retries: 5

  # .NET API Application
  api:
    build:
      context: .
      dockerfile: src/RealEstate.API/Dockerfile.prod
    container_name: realestate-api
    ports:
      - "7269:5268"  # Map to app's natural port inside container
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=realestate;Username=realestateuser;Password=123
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5268
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - realestate-network
    volumes:
      # Use a named volume instead of bind mount to avoid overwriting container files
      - realestate-images:/app/wwwroot/images
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5268/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Shared volumes
volumes:
  postgres-data:
    name: realestate-postgres-data
  realestate-images:
    name: realestate-images

# Shared networks
networks:
  realestate-network:
    name: realestate-network
